name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional, for installing dependencies)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (if you have any)
      run: npm install

    - name: Inject Webhook URL into JavaScript
      run: |
        # Replace the placeholder in script.js with the actual Discord webhook URL from GitHub Secrets
        sed -i 's|DISCORD_WEBHOOK_URL|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' public/script.js

    - name: Build and deploy to GitHub Pages
      run: |
        # Add any build steps here if you need them, otherwise just deploy
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages  # The branch you want to deploy to
        folder: public    # The folder where your built website is located
