name: Inject Discord Webhook URL into script.js

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  inject-discord-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add Mask for Discord Webhook URL (for security)
      run: echo "::add-mask::${{ secrets.DISCORD_WEBHOOK_URL }}"  # Mask the webhook URL for security in logs

    - name: Inject Discord Webhook URL into script.js
      run: |
        # Replace the placeholder in sushi/script.js with the actual Discord webhook URL from GitHub Secrets
        sed -i 's|DISCORD_WEBHOOK_URL|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' sushi/script.js
        echo "Discord Webhook URL has been injected into script.js."

    - name: Commit and push changes to GitHub
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add sushi/script.js  # Add the modified script.js file
        git commit -m "Inject Discord Webhook URL into script.js"
        git push
