name: Inject Discord Webhook URL into script.js

on:
  push:
    branches:
      - main  # This workflow runs when changes are pushed to the main branch.

jobs:
  inject-discord-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Step to checkout the repository

    - name: Mask Discord Webhook URL
      run: echo "::add-mask::${{ secrets.DISCORD_WEBHOOK_URL }}"  # Masks the secret to prevent it from being exposed in logs

    - name: Inject Webhook URL into script.js
      run: |
        # Use 'sed' to replace the placeholder with the actual webhook URL in script.js
        sed -i 's|DISCORD_WEBHOOK_URL|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' sushi/script.js
        cat sushi/script.js  # Debug: print the content of script.js to verify replacement

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add sushi/script.js
        git commit -m "Inject Discord webhook URL into script.js"
        git push
