name: Inject Discord Webhook into script.js

on:
  push:
    branches:
      - main  # Deploys when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Inject the Discord webhook URL into script.js using secret-injector-action
    - name: Inject Discord Webhook URL into script.js
      uses: alessandro-marcantoni/secret-injector-action@v0.1.0
      with:
        secrets: ${{ toJson(secrets) }}  # Inject secrets defined in your repository's Secrets section
        env: ${{ toJson(env) }}  # Inject environment variables (optional, if you have any)

    # Step 3: Build and deploy to GitHub Pages
    - name: Build and deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages  # The branch you want to deploy to
        folder: public    # The folder where your built website is located
