name: Inject Discord Webhook URL into script.js

on:
  push:
    branches:
      - main  # This workflow runs when changes are pushed to the main branch.

jobs:
  inject-discord-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mask Discord Webhook URL
        run: echo "::add-mask::${{ secrets.DISCORD_WEBHOOK_URL }}"  # Mask the secret to prevent it from being exposed in logs

      - name: Inject Webhook URL into script.js
        run: |
          # Replace 'LOLYOUCRAZY' placeholder with the actual webhook URL from GitHub Secrets in sushi/script.js
          sed -i 's|LOLYOUCRAZY|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' sushi/script.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sushi/script.js
          git commit -m "Inject Discord Webhook URL"
          git push
