name: Inject Discord Webhook URL into script.js

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  inject-discord-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Mask Discord Webhook URL
      run: echo "::add-mask::${{ secrets.DISCORD_WEBHOOK_URL }}"

    - name: Inject Webhook URL into script.js
      run: sed -i 's|DISCORD_WEBHOOK_URL|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' sushi/script.js
