name: Inject Secrets into script.js

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
    - uses: actions/checkout@v2

      # Inject the Discord webhook URL into script.js
    - name: Inject Discord Webhook URL into script.js
      run: |
        sed -i 's|DISCORD_WEBHOOK_URL|'"${{ secrets.DISCORD_WEBHOOK_URL }}"'|g' sushi/script.js

      # Optional: Print out the contents of script.js to verify
    - name: Verify script.js contents
      run: |
        cat sushi/script.js
